### PR TITLE
Adding puzzle functionality, issue #2

### PR DESCRIPTION
**Pull request by ppeloton**
A new PR to add new functionality to puzzle mode:

- button to get a hint. Proposal is to add a separate map for hints in order to keep flexibility (possibility to give multiple hints starting from small hints)
- button to show the next move of the puzzle
- button to show whole solution of puzzle

Added a small timeout when computer reply is played.

Two small issues remain:
- I was not able to get the icon for the 'get hint' button to work (fa-lightbulb). Maybe someone can help here (I am also open for other icons, if they are seen as more appropriate for the buttons).
- Translations for texts in `locale` folder are missing. I can add them later (partly with the help of Google Translate or similar), if the changes are seen to be good enough to be merged.

Still the ticket #2 can be left open, as the functionalities need to be further developed and tested. I think the PR gives the users more functionality for use and testing, which improves discussions on further development.

### CODE REVIEW

**Comment by mliebelt** [comment]
I have done the "merge and rebase", to check it later then. From the first look, the changes seem to be not conflicting ...

**Comment by mliebelt** [comment]
Thank you a lot for providing that addition, I will try to understand why the fa-lightbulb icon is not shown. The UI is now (much) better, easier to understand, and a good starting point. Perhaps we will see some more improvements, but I don't think they are necessary. I like the way hints are added, that is understandable, and should be easy to use. Creating puzzles is hard, but that is a completely different topic then.

**Comment by mliebelt** [comment]
I found the reason, why the icon does not show up. I created (from my pro license of FontAwesome) a so called kit, and took a subset that has only the icons I wanted to use at that time. So I should be able to redo that process (somehow). I tried instead the public version, which then brings the former minimized ~300k version (which is already too big) to over 1MB then. I tried to understand the documentation about tree shaking (https://docs.fontawesome.com/apis/javascript/tree-shaking), but was not able to have something working.

So I will check if I am easily able to adapt the kit, and will update that then.

**Comment by ppeloton** [comment]
OK, great. Maybe a different icon is easier to implement if it is ready available. I also just added a new PR with translations of the new buttons.

**Comment by mliebelt** [comment]
Got it, will push it soon (branch). 
image

**Pull request merged**
